create table investimento (
	id bigint not null generated by default as identity,
	categoria_id bigint not null,
	codigo_ativo varchar(10) not null,
	valor_cota float not null,
	qtd_cotas int not null,
	data_compra timestamp not null,
	
	primary key (id)
)

tablespace pg_default;


alter table investimento add constraint fk_categoria_investimento foreign key (categoria_id) references categoria (id);